import { Suspense, useEffect, useLayoutEffect, useMemo, useState } from 'react';
import * as THREE from 'three';
import { Text } from '@react-three/drei';
import type { FinishType } from '@domain/entities/order-card';
import type { MonumentShape } from '@domain/entities/monument';
import { useStoneAlbedoTexture } from './use-stone-albedo-texture';
import { usePhotoTexture, type PhotoCrop } from './use-photo-texture';
import { createNaturalEngravedPhotoMaterial } from './engraved-photo-material';
import { createHeadstoneExtrudeGeometry } from './headstone-extrude-geometry';
import { slabFootprintCm } from '@application/pricing/monument-price';
import {
  finishToSurface,
  getInscriptionColors,
  isDarkStone as isDarkStoneName,
  isSeamlessStone,
  sampleStoneTextureStats,
  type StoneTextureStats
} from './stone-catalog';

export interface MonumentDimensionsCm {
  heightCm: number;
  widthCm: number;
  thicknessCm: number;
}

export interface BaseDimensionsCm {
  heightCm: number;
  widthCm: number;
  depthCm: number;
}

export interface InscriptionStyleHints {
  fontUrl?: string;
  letterSpacing: number;
  transform: 'none' | 'uppercase';
  /** Compensates for decorative fonts whose visible glyphs are smaller at the same point size. */
  fontScale?: number;
}

/** Geometry of the symmetric ogee-curve silhouette (`curvy` shape). All values are %
 * measured from the LEFT edge (X) and from the BOTTOM (Y). The left side is generated by
 * mirroring the right anchors across X=50, so editing the right side in the SVG editor
 * drives BOTH sides at once. Shared between the 3D builder and the editor preview. */
export const CURVY_GEOMETRY = {
  /** Right side ogee anchors (bottom-up). `midAnchor` sits roughly where the silhouette
   * pinches inward (~28 % H), `bulgeAnchor` is the slight outward swell (~55 % H), and
   *  `topAnchor` is where the top arch starts (the X distance from centre defines the
   * shoulder width of the arch). */
  midAnchorX: 78,
  midAnchorY: 28,
  bulgeAnchorX: 84,
  bulgeAnchorY: 55,
  topAnchorX: 70,
  topAnchorY: 88,
  /** Apex of the top arch — the silhouette's highest point. */
  apexX: 50,
  apexY: 100
} as const;

/** Geometry of the integrated cross protrusion on the `cross-top` shape (% of bounding box,
 * measured from the LEFT edge for X and from the BOTTOM for Y). Shared as a single source
 * of truth between the 3D builder (`buildCrossTopShape`) and the SVG editor preview
 *  (`docs/prototypy/shape-preview.html`) so both renders stay in lock-step. */
export const CROSS_TOP_GEOMETRY = {
  /** Pillar (vertical bar) X bounds — narrow centred column above the crossbar. */
  pillarLeftPct: 78,
  pillarRightPct: 86,
  /** Pillar top, slightly above the bounding box's nominal 100 %. The 3D model treats
   *  `heightM` as the BODY height; the cross is allowed to protrude above by design. */
  pillarTopPct: 100,
  /** Horizontal arm (crossbar) — wider band sitting BELOW the pillar. Its right edge is
   * flush with the body's right edge (100 %); the left edge sticks out a bit past the
   * pillar. */
  crossbarLeftPct: 70,
  crossbarBottomPct: 90,
  crossbarTopPct: 95
} as const;

export type MonumentDecoration = 'none' | 'portrait' | 'cross';

/** Tombstone slab variant: none, half (front cover only) or full (covers the whole grave). */
export type TombstoneSlabVariant = 'none' | 'half' | 'full';

/** Single stela or a double monument (two stelas side by side on a shared base). */
export const DEFAULT_INSCRIPTION_STYLE: InscriptionStyleHints = {
  letterSpacing: 0,
  transform: 'none',
  fontScale: 1
};

interface MonumentModelProps {
  textureUrl?: string;
  materialName?: string;
  finish: FinishType;
  dimensions: MonumentDimensionsCm;
  /** Custom base (pedestal) dimensions. When missing, derived from the headstone. */
  baseDimensions?: BaseDimensionsCm;
  inscription: string;
  name?: string;
  dates?: string;
  inscriptionStyle?: InscriptionStyleHints;
  shape?: MonumentShape;
  showCross?: boolean;
  /** Цветник — small flower planter sitting in front of the base. */
  showFlowerbed?: boolean;
  /** Плита надгробная — none, half (front cover) or full (whole grave). */
  tombstoneSlab?: TombstoneSlabVariant;
  /** Slab thickness preset, typically 5 or 8 cm. */
  slabThicknessCm?: number;
  /** Decoration on the headstone face: engraved portrait or engraved cross. */
  decoration?: MonumentDecoration;
  /** Optional portrait photo (data URL) engraved onto the face. */
  photoUrl?: string;
  /** Interactive crop — which region of the source photo appears on the stone. */
  photoCrop?: PhotoCrop;
  /** Live engraving adjustments for the on-stone portrait (user-tunable per material).
   * brightness: −0.4..0.4 tonal shift; contrast: 0.5..2.5 multiplier; blend: 0..1 where
   *  0 = opaque/max-visible and 1 = strongly dissolves into the stone. */
  photoBrightness?: number;
  photoContrast?: number;
  photoBlend?: number;
  /** Single stela (default) or a double monument with two stelas side by side. */
}

const CM_TO_M = 0.01;
const TEXT_LINE_HEIGHT = 1.15;

/** `Texture.image` is `any` in three: it may be an <img>, a <video>, a <canvas> or an
 *  ImageBitmap, and only some of those carry `naturalWidth` / `videoWidth`. Read the
 * intrinsic size through optional fields rather than narrowing to one element type. */
type TextureBitmapSource = Partial<
  Pick<HTMLImageElement, 'naturalWidth' | 'naturalHeight'> &
    Pick<HTMLVideoElement, 'videoWidth' | 'videoHeight'> &
    Pick<HTMLCanvasElement, 'width' | 'height'>
>;

const getTextureBitmapSize = (map: THREE.Texture): { w: number; h: number } => {
  const img = map.image as TextureBitmapSource | null | undefined;
  if (!img) return { w: 1, h: 1 };
  const w = img.naturalWidth || img.videoWidth || img.width || 0;
  const h = img.naturalHeight || img.videoHeight || img.height || 0;
  return w > 0 && h > 0 ? { w, h } : { w: 1, h: 1 };
};

/** Granit o równym ziarnie: kafelkujemy. Kamień z żyłami / dużym rysunkiem: jedna płyta. */
const applyAlbedoTextureTiling = (
  map: THREE.Texture,
  spanM: number,
  materialName: string | undefined
) => {
  if (isSeamlessStone(materialName)) {
    map.wrapS = map.wrapT = THREE.ClampToEdgeWrapping;
    map.repeat.set(1, 1);
    map.center.set(0.5, 0.5);
    map.offset.set(0, 0);
    map.needsUpdate = true;
    return;
  }

  const base = THREE.MathUtils.clamp(1.8 / Math.max(0.35, spanM), 0.65, 3.2);
  const { w, h } = getTextureBitmapSize(map);
  const ratio = h / w;

  map.wrapS = map.wrapT = THREE.RepeatWrapping;
  map.repeat.set(base, base * ratio);
  map.center.set(0.5, 0.5);
  map.offset.set(0, 0);
  map.needsUpdate = true;
};

/** Szerokość przeciętnego znaku w jednostkach fontSize, zanim doliczymy letterSpacing.
 *  Cyrylica jest w naszych krojach o 10–15 % szersza od łacinki (przemierzone na obecnym
 * zestawie plików w /fonts: 0,51–0,76 em wobec 0,44–0,69 em), więc ten sam napis po rosyjsku
 * zajmuje więcej miejsca. Przy wspólnym 0,7 prognoza dla najszerszego kroju — Ruslan Display —
 * wychodziła za niska, a za niska prognoza to nachodzące na siebie bloki tekstu, dlatego dla
 * cyrylicy bierzemy zapas. Wymiana krojów nie ruszyła tych wartości: zakresy wyszły te same. */
export const baseCharWidth = (text: string) => (/[Ѐ-ӿ]/.test(text) ? 0.78 : 0.7);

/** Słowo nie łamane przez troika-three-text — liczymy linie po granicach wyrazów (a nie zaokrąglając total/charsPerLine),
 * inaczej "John A. Smith" mieści się rzekomo w 2 liniach, a faktycznie wpada w 3 (każde słowo osobno). */
export const wordAwareLineCount = (value: string, charsPerLine: number) => {
  const normalizedLimit = Math.max(1, Math.floor(charsPerLine));
  let total = 0;
  for (const rawLine of value.split('\n')) {
    const words = rawLine.trim().split(/\s+/).filter(Boolean);
    if (words.length === 0) continue;
    let lines = 1;
    let used = 0;
    for (const word of words) {
      const need = used === 0 ? word.length : used + 1 + word.length;
      if (need <= normalizedLimit) {
        used = need;
      } else {
        lines += 1;
        used = word.length;
      }
    }
    total += lines;
  }
  return Math.max(0, total);
};

// --- Buildery kształtów ---
const buildClassicShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const halfWidth = widthM / 2;
  const shoulderInset = Math.max(0.03, widthM * 0.14);
  const neckInset = Math.max(0.05, widthM * 0.22);
  const bodyHeight = Math.max(0.06, heightM - widthM * 0.48);
  const shoulderY = bodyHeight * 0.74;
  const neckY = bodyHeight * 0.9;
  const crownY = heightM;
  shape.moveTo(-halfWidth, 0);
  shape.lineTo(halfWidth, 0);
  shape.lineTo(halfWidth - shoulderInset, shoulderY);
  shape.lineTo(halfWidth - neckInset, neckY);
  shape.quadraticCurveTo(0, crownY, -(halfWidth - neckInset), neckY);
  shape.lineTo(-(halfWidth - shoulderInset), shoulderY);
  shape.lineTo(-halfWidth, 0);
  return shape;
};

const buildRoundedShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const halfWidth = widthM / 2;
  const bodyHeight = Math.max(0.05, heightM - halfWidth);
  shape.moveTo(-halfWidth, 0);
  shape.lineTo(halfWidth, 0);
  shape.lineTo(halfWidth, bodyHeight);
  shape.absarc(0, bodyHeight, halfWidth, 0, Math.PI, false);
  shape.lineTo(-halfWidth, 0);
  return shape;
};

const buildGothicShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const halfWidth = widthM / 2;
  const bodyHeight = Math.max(0.05, heightM - widthM * 0.55);
  shape.moveTo(-halfWidth, 0);
  shape.lineTo(halfWidth, 0);
  shape.lineTo(halfWidth, bodyHeight);
  shape.quadraticCurveTo(halfWidth, heightM, 0, heightM);
  shape.quadraticCurveTo(-halfWidth, heightM, -halfWidth, bodyHeight);
  shape.lineTo(-halfWidth, 0);
  return shape;
};

const buildHeartShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const halfWidth = widthM / 2;
  const bodyHeight = Math.max(0.05, heightM - widthM * 0.6);
  const heartTop = heightM * 0.92;
  shape.moveTo(-halfWidth, 0);
  shape.lineTo(halfWidth, 0);
  shape.lineTo(halfWidth, bodyHeight);
  shape.bezierCurveTo(
    halfWidth,
    heartTop,
    halfWidth * 0.55,
    heartTop * 1.04,
    0,
    bodyHeight + (heartTop - bodyHeight) * 0.55
  );
  shape.bezierCurveTo(
    -halfWidth * 0.55,
    heartTop * 1.04,
    -halfWidth,
    heartTop,
    -halfWidth,
    bodyHeight
  );
  shape.lineTo(-halfWidth, 0);
  return shape;
};

const buildCrossShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const halfWidth = widthM / 2;
  const bodyHeight = Math.max(0.05, heightM * 0.62);
  const armHeight = heightM * 0.12;
  const armY = heightM * 0.78;
  const armWidth = widthM * 0.55;
  const stemWidth = widthM * 0.22;
  shape.moveTo(-halfWidth, 0);
  shape.lineTo(halfWidth, 0);
  shape.lineTo(halfWidth, bodyHeight);
  shape.lineTo(stemWidth, bodyHeight);
  shape.lineTo(stemWidth, armY);
  shape.lineTo(armWidth, armY);
  shape.lineTo(armWidth, armY + armHeight);
  shape.lineTo(stemWidth, armY + armHeight);
  shape.lineTo(stemWidth, heightM);
  shape.lineTo(-stemWidth, heightM);
  shape.lineTo(-stemWidth, armY + armHeight);
  shape.lineTo(-armWidth, armY + armHeight);
  shape.lineTo(-armWidth, armY);
  shape.lineTo(-stemWidth, armY);
  shape.lineTo(-stemWidth, bodyHeight);
  shape.lineTo(-halfWidth, bodyHeight);
  shape.lineTo(-halfWidth, 0);
  return shape;
};

/** Modern minimalist stele — nearly straight sides with a small diagonal chamfer on the top corners,
 * and a very slight taper (top is ~5 % narrower than the base). */
const buildSteleShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  const chamfer = Math.min(0.05, widthM * 0.07);
  const taper = widthM * 0.03;
  shape.moveTo(-hw, 0);
  shape.lineTo(hw, 0);
  shape.lineTo(hw - taper, heightM - chamfer);
  shape.lineTo(hw - taper - chamfer, heightM);
  shape.lineTo(-(hw - taper - chamfer), heightM);
  shape.lineTo(-(hw - taper), heightM - chamfer);
  shape.lineTo(-hw, 0);
  return shape;
};

/** Concave "wave" stele — both sides curve inward (concave) to form a dramatic waist at ~42 % of
 * the height, then flare back out to broad shoulders with a semicircular crown.
 *  Common in Polish / Eastern-European memorial catalogs. */
const buildConcaveShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  const waist = widthM * 0.17;
  const wy = heightM * 0.42;
  const si = widthM * 0.04;
  const bh = Math.max(0.05, heightM - (hw - si));
  shape.moveTo(-hw, 0);
  shape.lineTo(hw, 0);
  shape.bezierCurveTo(hw, heightM * 0.14, hw - waist * 0.4, wy * 0.65, hw - waist, wy);
  shape.bezierCurveTo(hw - waist, wy + heightM * 0.13, hw - si, bh * 0.88, hw - si, bh);
  shape.absarc(0, bh, hw - si, 0, Math.PI, false);
  shape.bezierCurveTo(-(hw - si), bh * 0.88, -(hw - waist), wy + heightM * 0.13, -(hw - waist), wy);
  shape.bezierCurveTo(-(hw - waist * 0.4), wy * 0.65, -hw, heightM * 0.14, -hw, 0);
  return shape;
};

/** Asymmetric wave-top stele — specific Russian / Polish catalogue silhouette (tuned
 * interactively in the SVG editor and confirmed by the user).
 *
 *  Profile:
 *  – sides flare outward going up: base is inset by 16.5 % per side, top is full width,
 *  – left edge tops out at  91   % H,
 *  – right edge tops out at 83.5 % H,
 *  – top wave is a single cubic Bezier with control points producing a soft apex slightly
 * left of centre (cp2 sits ABOVE heightM at 103 %).
 *
 *  All percentages live in the standard `widthM` × `heightM` frame the other builders use,
 * so the rest of the model (base / pedestal / slab / decoration) works unchanged. */
const buildAsymmetricShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;

  const BOTTOM_TAPER = 0.165;
  const taperInset = widthM * BOTTOM_TAPER;

  const leftTopY = heightM * 0.91;
  const rightTopY = heightM * 0.835;

  /** Bezier control points expressed in the same centred frame.
   * cp1 sits near the RIGHT edge (curve leaves right top point toward this point).
   * cp2 sits near the LEFT edge (curve arrives at left top point from this point).
   *  Editor values are % of widthM from the LEFT side; we map them by subtracting hw. */
  const cp1x = -hw + widthM * 0.68;
  const cp1y = heightM * 0.825;
  const cp2x = -hw + widthM * 0.52;
  const cp2y = heightM * 1.03;

  shape.moveTo(-hw + taperInset, 0);
  shape.lineTo(hw - taperInset, 0);
  shape.lineTo(hw, rightTopY);
  shape.bezierCurveTo(cp1x, cp1y, cp2x, cp2y, -hw, leftTopY);
  shape.lineTo(-hw + taperInset, 0);

  return shape;
};

/** Dome-top stele — gentle peaked silhouette tuned interactively in the SVG editor.
 *
 *  Profile (3 anchors → 2 cubic Bezier segments stitched at the central anchor):
 *  – left edge tops out at 79.43 % H, right at 79.95 % H (near-symmetric),
 *  – central anchor sits at (x = 51.80 %, y = 88.43 % H) — peak slightly left of centre,
 *  – control handles produce a soft, low arch (the rise from edge to apex is only ~ 9 % H).
 *
 *  Sides are straight vertical (no taper). All percentages live in the standard widthM/heightM
 * reference frame — `pct(x)` converts editor "% from the LEFT" to the model's centred frame. */
const buildDomeShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  const px = (pct: number) => (pct / 100 - 0.5) * widthM;
  const py = (pct: number) => (pct / 100) * heightM;

  shape.moveTo(-hw, 0);
  shape.lineTo(+hw, 0);
  shape.lineTo(+hw, py(79.95));

  /** Right segment: from the right edge anchor #0 → central anchor #1.
   * hOut #0 = (70.25, 83.93), hIn #1 = (71.60, 88.61), anchor #1 = (51.80, 88.43). */
  shape.bezierCurveTo(px(70.25), py(83.93), px(71.6), py(88.61), px(51.8), py(88.43));

  /** Left segment: from central anchor #1 → left edge anchor #2.
   * hOut #1 = (32.00, 88.26), hIn #2 = (33.80, 84.97), anchor #2 = (0, 79.43). */
  shape.bezierCurveTo(px(32.0), py(88.26), px(33.8), py(84.97), -hw, py(79.43));

  shape.lineTo(-hw, 0);
  return shape;
};

/** Arc-top stele — single soft asymmetric arch tuned interactively in the SVG editor.
 *
 *  Profile (2 anchors → single cubic Bezier segment):
 *  – left edge tops out at  79.26 % H, right at 79.95 % H — nearly equal,
 *  – control hOut at the right anchor points slightly below it (64.85, 77.13) — tangent
 * eases the curve out almost horizontally,
 *  – control hIn at the left anchor sits high above it (36.05, 94.78), pulling the apex up.
 *
 *  Net effect: a low, soft arch with its apex ≈ 86 % H shifted to ≈ −0.35 · hw (left of
 * centre). Straight vertical sides, no taper. */
const buildArcShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  const px = (pct: number) => (pct / 100 - 0.5) * widthM;
  const py = (pct: number) => (pct / 100) * heightM;

  shape.moveTo(-hw, 0);
  shape.lineTo(+hw, 0);
  shape.lineTo(+hw, py(79.95));
  shape.bezierCurveTo(px(64.85), py(77.13), px(36.05), py(94.78), -hw, py(79.26));
  shape.lineTo(-hw, 0);
  return shape;
};

/** Steep-wave stele — generic asymmetric silhouette, straight vertical sides (no taper),
 * single cubic Bezier across the top with a noticeable height difference between the two
 * edges (96 % vs 78 %). Control points push past full height to produce a wave-like apex
 * above the upper left portion of the face. */
const buildWaveSteepShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  const leftTopY = heightM * 0.96;
  const rightTopY = heightM * 0.78;
  shape.moveTo(-hw, 0);
  shape.lineTo(hw, 0);
  shape.lineTo(hw, rightTopY);
  shape.bezierCurveTo(hw * 0.55, heightM * 1.0, -hw * 0.25, heightM * 1.05, -hw, leftTopY);
  shape.lineTo(-hw, 0);
  return shape;
};

/** Wavy-top asymmetric stele with an integrated cross protruding from the top-right corner.
 *  The cross is a SOLID part of the silhouette (same granite block, same material) — not a
 * separate decoration mesh — so it casts shadows and reads as one monolithic stone.
 *
 *  Silhouette trace (clockwise from bottom-left):
 *   1. bottom edge,
 *   2. right edge straight up to the crossbar top,
 *   3. across-the-top-of-the-crossbar (right arm) → up the pillar's right side → across the
 * pillar's top → down the pillar's left side → across the top of the left arm → down the
 * crossbar's left side,
 *   4. cubic Bezier wave across the body's top, ending at the LEFT edge,
 *   5. left edge straight down to start.
 *
 *  The wave defaults are mild (one gentle dip + one gentle rise) — the user can swap them
 * in via the SVG editor preset `cross-top`. */
const buildCrossTopShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  const px = (pct: number) => (pct / 100 - 0.5) * widthM;
  const py = (pct: number) => (pct / 100) * heightM;

  const c = CROSS_TOP_GEOMETRY;

  shape.moveTo(-hw, 0);
  shape.lineTo(+hw, 0);
  shape.lineTo(+hw, py(c.crossbarTopPct));
  shape.lineTo(px(c.pillarRightPct), py(c.crossbarTopPct));
  shape.lineTo(px(c.pillarRightPct), py(c.pillarTopPct));
  shape.lineTo(px(c.pillarLeftPct), py(c.pillarTopPct));
  shape.lineTo(px(c.pillarLeftPct), py(c.crossbarTopPct));
  shape.lineTo(px(c.crossbarLeftPct), py(c.crossbarTopPct));
  shape.lineTo(px(c.crossbarLeftPct), py(c.crossbarBottomPct));

  /** Body wave from (crossbarLeft, crossbarBottom) curving across to the left edge. Default
   * control points produce a mild S-shape — one shallow dip on the right half (around
   *  X = 50 %, Y ≈ 84 %) and a slight rise on the left half (around X = 13 %, Y ≈ 89 %). */
  shape.bezierCurveTo(px(50), py(80), px(20), py(96), -hw, py(86));

  shape.lineTo(-hw, 0);
  return shape;
};

/** Symmetric ogee-curve silhouette — wide flat base, both sides undulate (pinch in around
 *  28 % H, swell back out around 55 % H, then narrow into a soft top arch with apex near
 * the centre at 100 % H).
 *
 *  Built from the shared `CURVY_GEOMETRY` constants (also used by the SVG editor preview)
 * so what the user sketches in the editor matches what the 3D model renders, pixel for
 * pixel. The left side is generated by mirroring the right-side anchor X coordinates
 * across X = 50 % — no editor knobs for the left side because the silhouette is forced
 * symmetric (matches the Russian Orthodox catalogue style this shape is modelled after).
 *
 *  Control-point construction is "auto-smooth": each handle sits roughly 30 % of the way
 * along the chord between adjacent anchors, in the chord's direction. This produces a
 * visually smooth curve without exposing 8 separate handles to the user. */
const buildCurvyShape = (widthM: number, heightM: number) => {
  const shape = new THREE.Shape();
  const hw = widthM / 2;
  /** Convert a "% from the left edge" value to the 3D model's centred X frame. */
  const px = (pct: number) => (pct / 100 - 0.5) * widthM;
  const py = (pct: number) => (pct / 100) * heightM;

  const g = CURVY_GEOMETRY;

  /** Anchor positions, right side bottom-up. */
  const a0 = { x: 100, y: 0 };
  const a1 = { x: g.midAnchorX, y: g.midAnchorY };
  const a2 = { x: g.bulgeAnchorX, y: g.bulgeAnchorY };
  const a3 = { x: g.topAnchorX, y: g.topAnchorY };
  const a4 = { x: g.apexX, y: g.apexY };

  /** Mirror across X = 50 % to obtain the matching left-side anchors. */
  const mirror = (p: { x: number; y: number }) => ({ x: 100 - p.x, y: p.y });
  const a5 = mirror(a3);
  const a6 = mirror(a2);
  const a7 = mirror(a1);
  const a8 = mirror(a0);

  /** Tangent handle along the chord between two anchors at a fixed ratio of the chord's
   * length — produces visually balanced cubic Beziers. */
  const handle = (from: { x: number; y: number }, to: { x: number; y: number }, ratio: number) => ({
    x: from.x + (to.x - from.x) * ratio,
    y: from.y + (to.y - from.y) * ratio
  });
  /** Each segment uses the same incoming/outgoing handle ratio — visually consistent
   * curvature across the silhouette. 0.45 is wide enough to give a definite curve
   * without pulling the shape away from the anchor positions. */
  const R = 0.45;

  shape.moveTo(-hw, 0);
  shape.lineTo(+hw, 0);

  /** Right side: a0 → a1 → a2 → a3 (three cubic Beziers). */
  let cp1 = handle(a0, a1, R);
  let cp2 = handle(a1, a0, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a1.x), py(a1.y));

  cp1 = handle(a1, a2, R);
  cp2 = handle(a2, a1, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a2.x), py(a2.y));

  cp1 = handle(a2, a3, R);
  cp2 = handle(a3, a2, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a3.x), py(a3.y));

  /** Top arch: a3 → a4 (apex) → a5. Two cubic Beziers, handles pulled UP so the apex sits
   * comfortably at the anchor instead of cutting through it. */
  cp1 = { x: a3.x, y: a4.y };
  cp2 = handle(a4, a3, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a4.x), py(a4.y));

  cp1 = handle(a4, a5, R);
  cp2 = { x: a5.x, y: a4.y };
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a5.x), py(a5.y));

  /** Left side mirror: a5 → a6 → a7 → a8. */
  cp1 = handle(a5, a6, R);
  cp2 = handle(a6, a5, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a6.x), py(a6.y));

  cp1 = handle(a6, a7, R);
  cp2 = handle(a7, a6, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), px(a7.x), py(a7.y));

  cp1 = handle(a7, a8, R);
  cp2 = handle(a8, a7, R);
  shape.bezierCurveTo(px(cp1.x), py(cp1.y), px(cp2.x), py(cp2.y), -hw, 0);

  return shape;
};

const buildShape = (kind: MonumentShape, widthM: number, heightM: number) => {
  switch (kind) {
    case 'rounded':
      return buildRoundedShape(widthM, heightM);
    case 'gothic':
      return buildGothicShape(widthM, heightM);
    case 'heart':
      return buildHeartShape(widthM, heightM);
    case 'stele':
      return buildSteleShape(widthM, heightM);
    case 'concave':
      return buildConcaveShape(widthM, heightM);
    case 'asymmetric':
      return buildAsymmetricShape(widthM, heightM);
    case 'wave-steep':
      return buildWaveSteepShape(widthM, heightM);
    case 'dome':
      return buildDomeShape(widthM, heightM);
    case 'arc':
      return buildArcShape(widthM, heightM);
    case 'cross-top':
      return buildCrossTopShape(widthM, heightM);
    case 'curvy':
      return buildCurvyShape(widthM, heightM);
    case 'cross':
      return buildCrossShape(widthM, heightM);
    case 'classic':
    default:
      return buildClassicShape(widthM, heightM);
  }
};

export const MonumentModel = ({
  textureUrl,
  materialName,
  finish,
  dimensions,
  baseDimensions,
  inscription,
  name,
  dates,
  inscriptionStyle = DEFAULT_INSCRIPTION_STYLE,
  shape: shapeKind = 'classic',
  showCross = false,
  showFlowerbed = false,
  tombstoneSlab = 'full',
  slabThicknessCm = 5,
  decoration = 'none',
  photoUrl,
  photoCrop,
  photoBrightness = 0,
  photoContrast = 1.1,
  photoBlend = 0.08,
}: MonumentModelProps) => {
  const widthM = dimensions.widthCm * CM_TO_M;
  const heightM = dimensions.heightCm * CM_TO_M;
  const thicknessM = Math.max(0.04, dimensions.thicknessCm * CM_TO_M);

  /** Double-monument geometry: two stelas of the same shape/material/size sit side-by-side on a
   * single shared base — visually "glued together" with a hairline seam down the middle.
   *
   *  Each extruded headstone has an 8 mm bevel on every edge (see `createHeadstoneExtrudeGeometry`).
   *  If we positioned the two centers exactly `widthM` apart, those bevels would create a visible
   *  ~16 mm V-groove between the stelas. We compensate by pulling each stela inward by one bevel
   * width — so when the user dials the gap to 0, the bevels merge into a clean seam instead of a
   * furrow, and a positive gap value still produces the expected visible spacing. */
  const stelaOffsetsX = [0];
  /** Total horizontal extent of the headstone footprint (used by base/slab width derivations). */
  const stelaSpanM = widthM;

  /** Base (pedestal) can be set explicitly by the user — otherwise derived from the full stela span.
   *  When the user-supplied width is too narrow to physically hold both stelas, we silently widen
   * the base to a sane floor; the slider keeps responding for further fine-tuning above that floor. */
  const derivedBaseWidth = widthM * 1.4;
  const baseWidth = baseDimensions
    ? Math.max(0.4, baseDimensions.widthCm * CM_TO_M)
    : derivedBaseWidth;
  const baseDepth = baseDimensions
    ? Math.max(0.15, baseDimensions.depthCm * CM_TO_M)
    : thicknessM * 2.6;
  const baseHeight = baseDimensions
    ? Math.max(0.04, baseDimensions.heightCm * CM_TO_M)
    : Math.max(0.08, Math.min(0.16, heightM * 0.1));
  const plinthWidth = baseWidth * 0.86;
  const plinthDepth = baseDepth * 0.82;
  const plinthHeight = Math.max(0.04, baseHeight * 0.55);

  /** Плита надгробная — wide flat slab covering the grave.
   *  Half = covers only the area in front of the base (≈half a typical grave length).
   *  Full = covers the whole grave from the base forward. */
  const slabHeight = Math.max(0.03, slabThicknessCm * CM_TO_M);
  /* Proportions shared with the price: the stone being drawn is the stone
     being charged for. See `slabFootprintCm`. */
  const slabFootprint = slabFootprintCm({
    variant: tombstoneSlab === 'none' ? 'full' : tombstoneSlab,
    baseWidthCm: baseWidth / CM_TO_M,
    baseDepthCm: baseDepth / CM_TO_M,
    stelaWidthCm: stelaSpanM / CM_TO_M,
    stelaThicknessCm: thicknessM / CM_TO_M
  })!;
  const slabWidth = slabFootprint.widthCm * CM_TO_M;
  const slabDepth = slabFootprint.depthCm * CM_TO_M;
  /** Push slab forward more for "half" — visually it stops short of fully covering the grave. */
  const slabForwardOffset = tombstoneSlab === 'half' ? slabDepth * 0.32 : slabDepth * 0.18;
  const hasSlab = tombstoneSlab !== 'none';

  /** Цветник — rectangular planter sitting just in front of the base. */
  const flowerbedWidth = baseWidth * 0.95;
  const flowerbedDepth = Math.max(baseDepth * 0.6, thicknessM * 1.8);
  const flowerbedHeight = Math.max(0.08, baseHeight * 0.7);
  const flowerbedWall = Math.max(0.025, flowerbedDepth * 0.2);

  /** Stack everything bottom-up. When the slab is hidden the base sits on the ground. */
  const slabTopY = hasSlab ? slabHeight : 0;
  const baseY = slabTopY + baseHeight / 2;
  const plinthY = slabTopY + baseHeight + plinthHeight / 2;
  const headstoneBaseY = slabTopY + baseHeight + plinthHeight - 0.005;

  const albedoMap = useStoneAlbedoTexture(textureUrl, materialName);
  const spanM =
    Math.max(dimensions.heightCm, dimensions.widthCm, dimensions.thicknessCm * 2) * CM_TO_M;

  /** Stone luminance class — drives:
   *  – text fill / outline colour (light letters on dark stone, dark letters on light stone),
   *  – portrait engraving polarity (white-on-black etch on granite, dark-on-light on marble),
   *  – default niche plate colour.
   *  Defined early so the photo material below can branch on it. */
  const isDarkStone = isDarkStoneName(materialName);

  /** Actual average luminance (0..1) of the currently selected stone, sampled from its
   * albedo texture. This drives the portrait engraving so it adapts to ANY material:
   * the photo dissolves where its tone matches the stone and stays opaque where it
   * contrasts — light marks on dark granite, dark marks on pale marble, both extremes on
   * a mid-gray stone. Seeded from the dark/light class so the first frame is sensible
   * before the texture has been sampled. */
  const [stoneLuma, setStoneLuma] = useState<number>(isDarkStone ? 0.08 : 0.6);
  const [stoneTextureStats, setStoneTextureStats] = useState<StoneTextureStats | undefined>();

  useEffect(() => {
    const img = albedoMap.image as CanvasImageSource | undefined;
    if (!img) return;
    const stats = sampleStoneTextureStats(img);
    if (stats) {
      setStoneLuma(Math.min(1, Math.max(0, stats.meanLuma)));
      setStoneTextureStats(stats);
      return;
    }
    setStoneLuma(isDarkStone ? 0.08 : 0.6);
    setStoneTextureStats(undefined);
  }, [albedoMap, isDarkStone]);

  /** User portrait photo, only relevant for the portrait decoration. The hook
   * pre-bakes both the aspect crop and a soft edge vignette into the texture so this
   * component doesn't have to coordinate UV repeat/offset with shader-side masking. */
  const photoTexture = usePhotoTexture(
    decoration === 'portrait' ? photoUrl : undefined,
    'portrait',
    photoCrop
  );

  /** Photo material — renders the uploaded portrait as a laser-etched grayscale engraving.
   *
   *  On dark stone the bright pixels stay bright and the shadows fall back to the
   *  slab, which is how a frosted etch reads; on pale stone it is the other way
   *  round, a dark cut into a light face.
   *
   *  Edge softness is delegated to `usePhotoTexture`'s canvas-level vignette (applied
   * after background removal) — keeping the GPU shader simple avoids version-specific
   * issues with three.js shader chunk renames. */
  const photoMaterial = useMemo(() => {
    if (!photoTexture) return null;
    return createNaturalEngravedPhotoMaterial({
      photoMap: photoTexture,
      stoneMap: albedoMap,
      stoneRepeat: new THREE.Vector2(albedoMap.repeat.x, albedoMap.repeat.y),
      stoneLuma,
      photoBrightness,
      photoContrast,
      photoBlend
    });
  }, [photoTexture, albedoMap, stoneLuma, photoBrightness, photoContrast, photoBlend]);

  useEffect(() => () => photoMaterial?.dispose(), [photoMaterial]);

  useLayoutEffect(() => {
    applyAlbedoTextureTiling(albedoMap, spanM, materialName);
  }, [albedoMap, spanM, materialName]);

  useEffect(() => {
    const img = albedoMap.image as HTMLImageElement | undefined;
    if (!img || typeof img.addEventListener !== 'function') return;
    if (img.complete && (img.naturalWidth || img.width)) return;
    const onLoad = () => applyAlbedoTextureTiling(albedoMap, spanM, materialName);
    img.addEventListener('load', onLoad);
    return () => img.removeEventListener('load', onLoad);
  }, [albedoMap, spanM, materialName]);

  const stoneMaterial = useMemo(() => {
    const surface = finishToSurface(finish);
    return new THREE.MeshPhysicalMaterial({
      color: 0xffffff,
      map: albedoMap,
      roughness: surface.roughness,
      metalness: surface.metalness,
      clearcoat: surface.clearcoat,
      clearcoatRoughness: surface.clearcoatRoughness,
      envMapIntensity: surface.envMapIntensity
    });
  }, [albedoMap, finish]);

  useEffect(() => () => stoneMaterial.dispose(), [stoneMaterial]);

  useEffect(() => {
    if (!import.meta.env.DEV) return;
    console.debug(
      '[MonumentModel] Cień na płycie: headstone ma receiveShadow=false (nie bierze mapy cienia światła kierunkowego — usuwa prostokątne plamy / self-shadow na czole). Bazy dalej mogą go zbierać.'
    );
  }, []);

  const shape = useMemo(() => buildShape(shapeKind, widthM, heightM), [shapeKind, widthM, heightM]);

  /** Bevel depth of the extruded headstone. IMPORTANT: THREE.ExtrudeGeometry adds the bevel
   *  OUTSIDE the nominal [0, depth] range, so the real flat FRONT face of the stone sits at
   *  `depth + bevelThickness`, not at `depth`. Everything mounted on the face (photo niche,
   * plate, frame, engraved cross, text) must be offset from `frontFaceZ` below — otherwise
   * it gets buried inside the bevel and the stone occludes it. */
  const HEADSTONE_BEVEL_Z = 0.014;
  const extrudeSettings = useMemo(
    () => ({
      depth: thicknessM,
      bevelEnabled: true,
      bevelThickness: HEADSTONE_BEVEL_Z,
      bevelSize: HEADSTONE_BEVEL_Z,
      bevelSegments: 5,
      curveSegments: 48
    }),
    [thicknessM]
  );

  /** World-Z of the headstone's flat front face (see `HEADSTONE_BEVEL_Z`). */
  const frontFaceZ = thicknessM + HEADSTONE_BEVEL_Z;

  const headstoneGeometry = useMemo(
    () => createHeadstoneExtrudeGeometry(shape, extrudeSettings),
    [shape, extrudeSettings]
  );

  useEffect(() => () => headstoneGeometry.dispose(), [headstoneGeometry]);

  const bodyHeight = useMemo(() => {
    switch (shapeKind) {
      case 'cross':
        return heightM * 0.6;
      case 'heart':
        return Math.max(0.05, heightM - widthM * 0.6);
      case 'gothic':
        return Math.max(0.05, heightM - widthM * 0.55);
      case 'rounded':
        return Math.max(0.05, heightM - widthM / 2);
      case 'stele':
        return heightM * 0.93;
      case 'concave':
        return Math.max(0.05, heightM - (widthM / 2 - widthM * 0.04));
      /** Asymmetric (tapered) — lower top edge at 83.5 % H. */
      case 'asymmetric':
        return heightM * 0.835;
      /** Steep-wave generic — lower top edge at 78 % H. */
      case 'wave-steep':
        return heightM * 0.78;
      /** Dome — both top edges ≈ 79.4–79.95 % H; use the lower for safety. */
      case 'dome':
        return heightM * 0.794;
      /** Arc — left edge 79.26 % H (lower of the two), use that as the inscription ceiling. */
      case 'arc':
        return heightM * 0.793;
      /** Cross-top — wave runs between 86 % (left) and 90 % (right at crossbar base). Use the
       * lower edge for the inscription ceiling; the cross itself sits well above and doesn't
       * participate in the body-height calculation. */
      case 'cross-top':
        return heightM * 0.86;
      /** Curvy — sides curve smoothly up to the top arch which starts at ~88 % H; apex at
       *  100 % H. Use the shoulder height (88 %) as the inscription ceiling so the text never
       * bumps into the rounded crown. */
      case 'curvy':
        return heightM * 0.88;
      case 'classic':
      default:
        return Math.max(0.06, heightM - widthM * 0.48);
    }
  }, [shapeKind, heightM, widthM]);

  /** Za mały offset + faza extrude → z-fight przy orbicie (widać to częściej przy ostrym czole classic). */
  const textZ = frontFaceZ + 0.028;

  /** Klasyczny ma wąską „szyję” (≈0.56·width na neckY), więc bez marginesu napis dochodziłby do krawędzi.
   *  Krzyż ma tylko wąski trzon — jeszcze ciaśniej. Pozostałe są zbliżone do prostokąta. */
  const textMaxWidthFactor = (() => {
    switch (shapeKind) {
      case 'classic':
        return 0.66;
      case 'cross':
        return 0.38;
      case 'stele':
        return 0.84;
      case 'concave':
        return 0.56;
      /** Base is 16.5 % narrower than the top on each side, so the chord at the typical text
       * band (y ≈ 0.25–0.40 H) is ≈ 80 % of widthM. 0.7 leaves a safe inner margin. */
      case 'asymmetric':
        return 0.7;
      case 'wave-steep':
        return 0.78;
      /** Straight vertical sides + low arch leaves plenty of horizontal room for text. */
      case 'dome':
        return 0.82;
      case 'arc':
        return 0.82;
      /** Straight vertical sides; the cross protrusion is well above the text band, so the
       * whole width is usable for the inscription. */
      case 'cross-top':
        return 0.82;
      /** Curvy — at the typical inscription band (≈30 % H) the silhouette is at its pinched
       * point, only ~78 % of widthM wide. 0.62 leaves a safe inner margin. */
      case 'curvy':
        return 0.62;
      case 'rounded':
      case 'gothic':
      case 'heart':
      default:
        return 0.78;
    }
  })();
  const textMaxWidth = widthM * textMaxWidthFactor;

  /** Zachowawcza szerokość znaku (patrz `baseCharWidth`) plus spory wpływ letterSpacingu — inaczej
   * linie troiki wychodziły o 1 dłuższe niż nasza prognoza i bloki zachodziły na siebie. */
  const charFactor = baseCharWidth(`${inscription}${name}`) + inscriptionStyle.letterSpacing * 0.9;

  const transformText = (value: string) =>
    inscriptionStyle.transform === 'uppercase' ? value.toUpperCase() : value;

  /** Dopasowujemy fontSize tak, żeby:
   *  – najdłuższe słowo zmieściło się w jednej linii (nie wyłamie się w pojedynczy znak),
   *  – cały tekst nie zajął więcej niż `maxLines` linii (zwykle 1–2). */
  const autoFitFontSize = (text: string, desired: number, maxLines: number) => {
    if (!text) return desired;
    const words = text.split(/\s+/).filter(Boolean);
    const longestWord = words.reduce((m, w) => Math.max(m, w.length), 1);
    const sizeByWord = textMaxWidth / (longestWord * charFactor);
    const sizeByTotal =
      textMaxWidth / (Math.ceil(text.length / Math.max(1, maxLines)) * charFactor);
    return Math.min(desired, sizeByWord, sizeByTotal);
  };

  const baseSize = Math.max(0.04, Math.min(widthM * 0.13, bodyHeight * 0.14));

  const inscriptionColors = getInscriptionColors(materialName, stoneTextureStats);
  const textFillColor = inscriptionColors.fill;
  const textOutlineColor = inscriptionColors.outline;

  const commonTextProps = {
    color: textFillColor,
    outlineColor: textOutlineColor,
    /** A firm opposite-colour outline keeps lettering legible on veins and speckled granite. */
    outlineOpacity: 1,
    anchorX: 'center' as const,
    anchorY: 'middle' as const,
    textAlign: 'center' as const,
    maxWidth: textMaxWidth,
    letterSpacing: inscriptionStyle.letterSpacing,
    font: inscriptionStyle.fontUrl,
    /** Text always above stone and engraved photo (photo renderOrder = 3). */
    renderOrder: 5,
    depthOffset: -4,
    frustumCulled: false
  };

  const linesFor = (text: string, fontSize: number) => {
    if (!text || fontSize <= 0) return 0;
    const charsPerLine = Math.max(1, Math.floor(textMaxWidth / (fontSize * charFactor)));
    return wordAwareLineCount(text, charsPerLine);
  };

  /** Decoration (portrait or cross) goes onto the upper portion of the headstone face.
   *  We compute its size and Y center first, then narrow the text layout so the two don't overlap.
   *  When `layout='double'`, the same decoration kind is mirrored on each stela. */
  const decorationSize = (() => {
    if (decoration === 'none') return { w: 0, h: 0 };
    const w = widthM * (decoration === 'cross' ? 0.34 : decoration === 'portrait' ? 0.56 : 0.42);
    const h = decoration === 'portrait' ? w * 1.18 : decoration === 'cross' ? w * 1.7 : w;
    return { w, h };
  })();
  /** Portrait sits in the middle of the upper third of the stele. */
  const decorationCenterY = bodyHeight * (decoration === 'portrait' ? 0.76 : 0.74);
  const decorationBottomY = decorationCenterY - decorationSize.h / 2;
  const hasDecoration = decoration !== 'none';

  /** Shape-dependent text bounds are the same on both stelas (same shape, same widthM, same heightM).
   *  Computed once so we don't repeat the switch for each stela in a double monument. */
  const textBounds = (() => {
    const decorationGap = baseSize * (decoration === 'portrait' ? 0.9 : 0.45);
    const decorationTopLimit = hasDecoration
      ? Math.max(bodyHeight * 0.1, decorationBottomY - decorationGap)
      : Infinity;

    const shaped = (() => {
      switch (shapeKind) {
        case 'classic':
          return {
            desiredCenterY: bodyHeight * (decoration === 'portrait' ? 0.34 : 0.45),
            topLimit: bodyHeight * (decoration === 'portrait' ? 0.54 : 0.72),
            bottomLimit: bodyHeight * 0.06
          };
        case 'cross':
          return {
            desiredCenterY: bodyHeight * 0.5,
            topLimit: bodyHeight * 0.85,
            bottomLimit: bodyHeight * 0.1
          };
        case 'rounded':
          return {
            desiredCenterY: heightM * 0.5,
            topLimit: bodyHeight + widthM * 0.18,
            bottomLimit: bodyHeight * 0.1
          };
        case 'gothic':
          return {
            desiredCenterY: heightM * 0.46,
            topLimit: bodyHeight + (heightM - bodyHeight) * 0.3,
            bottomLimit: bodyHeight * 0.1
          };
        case 'heart':
          return {
            desiredCenterY: heightM * 0.42,
            topLimit: bodyHeight * 0.96,
            bottomLimit: bodyHeight * 0.1
          };
        case 'stele':
          return {
            desiredCenterY: bodyHeight * 0.42,
            topLimit: bodyHeight * 0.78,
            bottomLimit: bodyHeight * 0.08
          };
        case 'concave':
          return {
            desiredCenterY: heightM * 0.28,
            topLimit: heightM * 0.44,
            bottomLimit: bodyHeight * 0.06
          };
        case 'asymmetric':
          /** Text sits in the lower-middle band — wave top is reserved for the portrait / cross
           * engraving. Bottom margin is bigger than other shapes because the base is tapered:
           * a too-low line would touch the inward-sloping side. */
          return {
            desiredCenterY: heightM * 0.34,
            topLimit: heightM * 0.65,
            bottomLimit: bodyHeight * 0.14
          };
        case 'wave-steep':
          return {
            desiredCenterY: heightM * 0.34,
            topLimit: heightM * 0.62,
            bottomLimit: bodyHeight * 0.06
          };
        case 'dome':
          /** Top arch peaks at 88 % and edges are at 79 % — text can safely go up to ~66 %
           * before flirting with the curve. Inscription typically centred a bit higher than
           * asymmetric shapes because the arch makes the available band feel taller. */
          return {
            desiredCenterY: heightM * 0.36,
            topLimit: heightM * 0.66,
            bottomLimit: bodyHeight * 0.06
          };
        case 'arc':
          /** Apex ≈ 86 % H, edges ≈ 79 % — band is similar to dome but the apex is shifted
           * left, so we keep the same conservative top limit. */
          return {
            desiredCenterY: heightM * 0.36,
            topLimit: heightM * 0.64,
            bottomLimit: bodyHeight * 0.06
          };
        case 'cross-top':
          /** Wave varies 80–90 % H. The text band sits comfortably in the lower half — the
           * upper half is reserved for the portrait (which is centred on widthM = 0 and so
           * stays clear of the right-aligned cross protrusion). */
          return {
            desiredCenterY: heightM * 0.34,
            topLimit: heightM * 0.62,
            bottomLimit: bodyHeight * 0.06
          };
        case 'curvy':
          /** Pinch at ~28 % H means the inscription must stay above the narrowest band — we
           * bias text up into the broader middle (32–62 % H) where the silhouette swells. */
          return {
            desiredCenterY: heightM * 0.38,
            topLimit: heightM * 0.66,
            bottomLimit: bodyHeight * 0.12
          };
        default:
          return {
            desiredCenterY: bodyHeight * 0.5,
            topLimit: bodyHeight * 0.85,
            bottomLimit: bodyHeight * 0.08
          };
      }
    })();

    const topLimit = Math.min(shaped.topLimit, decorationTopLimit);
    const desiredCenterY = hasDecoration
      ? Math.min(shaped.desiredCenterY, (topLimit + shaped.bottomLimit) / 2)
      : shaped.desiredCenterY;
    return { ...shaped, topLimit, desiredCenterY };
  })();

  /** Pure helper — computes per-stela trimmed text + sizes + Y positions for a given inscription bundle.
   *  Called once per stela in the JSX below so each side can carry its own inscription/name/dates. */
  const computeStelaText = (inscriptionRaw: string, nameRaw: string, datesRaw: string) => {
    const inscriptionTrimmed = transformText(inscriptionRaw?.trim() ?? '');
    const nameTrimmed = transformText(nameRaw?.trim() ?? '');
    const datesTrimmed = datesRaw?.trim() ?? '';

    const fontScale = inscriptionStyle.fontScale ?? 1;
    const headerSize = autoFitFontSize(inscriptionTrimmed, baseSize * 0.85 * fontScale, 2);
    const nameSize = autoFitFontSize(nameTrimmed, baseSize * 1.3 * fontScale, 2);
    const datesSize = autoFitFontSize(datesTrimmed, baseSize * 0.9 * fontScale, 1);

    const headerLines = linesFor(inscriptionTrimmed, headerSize);
    const nameLines = linesFor(nameTrimmed, nameSize);
    const datesLines = linesFor(datesTrimmed, datesSize);

    const headerHeight = headerLines * headerSize * TEXT_LINE_HEIGHT;
    const nameHeight = nameLines * nameSize * TEXT_LINE_HEIGHT;
    const datesHeight = datesLines * datesSize * TEXT_LINE_HEIGHT;

    const blockGap = baseSize * 0.55;
    const visibleBlocks =
      (inscriptionTrimmed ? 1 : 0) + (nameTrimmed ? 1 : 0) + (datesTrimmed ? 1 : 0);
    const totalGaps = Math.max(0, visibleBlocks - 1) * blockGap;
    const totalTextHeight = headerHeight + nameHeight + datesHeight + totalGaps;

    const usableSpan = textBounds.topLimit - textBounds.bottomLimit;
    let textCenterY = textBounds.desiredCenterY;
    if (totalTextHeight <= usableSpan) {
      if (textCenterY + totalTextHeight / 2 > textBounds.topLimit) {
        textCenterY = textBounds.topLimit - totalTextHeight / 2;
      } else if (textCenterY - totalTextHeight / 2 < textBounds.bottomLimit) {
        textCenterY = textBounds.bottomLimit + totalTextHeight / 2;
      }
    } else {
      textCenterY = (textBounds.topLimit + textBounds.bottomLimit) / 2;
    }
    const textTopY = textCenterY + totalTextHeight / 2;

    let cursor = textTopY;
    const headerY = inscriptionTrimmed ? cursor - headerHeight / 2 : 0;
    if (inscriptionTrimmed) cursor -= headerHeight;
    if (inscriptionTrimmed && (nameTrimmed || datesTrimmed)) cursor -= blockGap;
    const nameY = nameTrimmed ? cursor - nameHeight / 2 : 0;
    if (nameTrimmed) cursor -= nameHeight;
    if (nameTrimmed && datesTrimmed) cursor -= blockGap;
    const datesY = datesTrimmed ? cursor - datesHeight / 2 : 0;

    return {
      inscriptionTrimmed,
      nameTrimmed,
      datesTrimmed,
      headerSize,
      nameSize,
      datesSize,
      headerY,
      nameY,
      datesY
    };
  };

  const stelaTexts = [computeStelaText(inscription, name ?? '', dates ?? '')];

  return (
    <group>
      {hasSlab && (
        <mesh
          position={[0, slabHeight / 2, slabForwardOffset]}
          receiveShadow
          material={stoneMaterial}
        >
          <boxGeometry args={[slabWidth, slabHeight, slabDepth]} />
        </mesh>
      )}

      {showFlowerbed &&
        (() => {
          /** Цветник siedzi z przodu podstawy: prostokątna obwódka z 4 ścianek + dno.
           *  Środek pozostaje pusty (wizualnie sugeruje miejsce na kwiaty). */
          const flowerbedFrontZ = baseDepth / 2 + flowerbedDepth / 2 + 0.01;
          const flowerbedBaseY = slabTopY + 0.005;
          const innerWidth = Math.max(0.02, flowerbedWidth - flowerbedWall * 2.8);
          const innerDepth = Math.max(0.02, flowerbedDepth - flowerbedWall * 2);
          return (
            <group position={[0, flowerbedBaseY, flowerbedFrontZ]}>
              <mesh receiveShadow material={stoneMaterial}>
                <boxGeometry args={[flowerbedWidth, 0.02, flowerbedDepth]} />
              </mesh>
              <mesh
                position={[0, flowerbedHeight / 2, -flowerbedDepth / 2 + flowerbedWall / 2]}
                receiveShadow
                material={stoneMaterial}
              >
                <boxGeometry args={[flowerbedWidth, flowerbedHeight, flowerbedWall]} />
              </mesh>
              <mesh
                position={[0, flowerbedHeight / 2, flowerbedDepth / 2 - flowerbedWall / 2]}
                receiveShadow
                material={stoneMaterial}
              >
                <boxGeometry args={[flowerbedWidth, flowerbedHeight, flowerbedWall]} />
              </mesh>
              <mesh
                position={[-flowerbedWidth / 2 + flowerbedWall / 2, flowerbedHeight / 2, 0]}
                receiveShadow
                material={stoneMaterial}
              >
                <boxGeometry args={[flowerbedWall, flowerbedHeight, innerDepth]} />
              </mesh>
              <mesh
                position={[flowerbedWidth / 2 - flowerbedWall / 2, flowerbedHeight / 2, 0]}
                receiveShadow
                material={stoneMaterial}
              >
                <boxGeometry args={[flowerbedWall, flowerbedHeight, innerDepth]} />
              </mesh>
              <mesh position={[0, 0.02 + flowerbedHeight * 0.68, 0]}>
                <boxGeometry args={[innerWidth, 0.01, innerDepth]} />
                <meshStandardMaterial color="#2a1d10" roughness={0.95} />
              </mesh>
            </group>
          );
        })()}

      <mesh position={[0, baseY, 0]} receiveShadow material={stoneMaterial}>
        <boxGeometry args={[baseWidth, baseHeight, baseDepth]} />
      </mesh>

      <mesh position={[0, plinthY, 0]} receiveShadow material={stoneMaterial}>
        <boxGeometry args={[plinthWidth, plinthHeight, plinthDepth]} />
      </mesh>

      {stelaOffsetsX.map((offsetX, stelaIdx) => {
        const txt = stelaTexts[stelaIdx];
        return (
          <group key={`stela-${stelaIdx}`} position={[offsetX, headstoneBaseY, -thicknessM / 2]}>
            <mesh
              castShadow={shapeKind !== 'classic'}
              receiveShadow={false}
              material={stoneMaterial}
              geometry={headstoneGeometry}
            />

            {hasDecoration &&
              (() => {
                const { w, h } = decorationSize;

                if (decoration === 'cross') {
                  /** Classic raised Latin cross carved from the same stone (relief on the face).
                   *  Square-section beams; the crossbar sits in the upper third. */
                  const beam = w * 0.26;
                  const reliefDepth = Math.max(0.02, widthM * 0.03);
                  const crossZ = frontFaceZ + reliefDepth / 2;
                  const crossbarY = h / 2 - h * 0.28;
                  return (
                    <group position={[0, decorationCenterY, 0]}>
                      <mesh position={[0, 0, crossZ]} castShadow material={stoneMaterial}>
                        <boxGeometry args={[beam, h, reliefDepth]} />
                      </mesh>
                      <mesh position={[0, crossbarY, crossZ]} castShadow material={stoneMaterial}>
                        <boxGeometry args={[w, beam, reliefDepth]} />
                      </mesh>
                    </group>
                  );
                }

                /* The portrait is etched into the polished face itself: no plate
                   behind it and no rim around it, which is what made earlier
                   versions look like a photograph stuck onto the stone. */
                return (
                  <group position={[0, decorationCenterY, 0]}>
                    {photoMaterial && (
                      <mesh
                        position={[0, 0, frontFaceZ + 0.012]}
                        material={photoMaterial}
                        renderOrder={3}
                      >
                        <planeGeometry args={[w, h]} />
                      </mesh>
                    )}
                  </group>
                );
              })()}

            <Suspense fallback={null}>
              {txt.inscriptionTrimmed && (
                <Text
                  {...commonTextProps}
                  position={[0, txt.headerY, textZ]}
                  fontSize={txt.headerSize}
                  outlineWidth={txt.headerSize * 0.11}
                  lineHeight={TEXT_LINE_HEIGHT}
                >
                  {txt.inscriptionTrimmed}
                </Text>
              )}
              {txt.nameTrimmed && (
                <Text
                  {...commonTextProps}
                  position={[0, txt.nameY, textZ]}
                  fontSize={txt.nameSize}
                  outlineWidth={txt.nameSize * 0.12}
                  lineHeight={TEXT_LINE_HEIGHT}
                >
                  {txt.nameTrimmed}
                </Text>
              )}
              {txt.datesTrimmed && (
                <Text
                  {...commonTextProps}
                  position={[0, txt.datesY, textZ]}
                  fontSize={txt.datesSize}
                  outlineWidth={txt.datesSize * 0.11}
                  lineHeight={TEXT_LINE_HEIGHT}
                >
                  {txt.datesTrimmed}
                </Text>
              )}
            </Suspense>
          </group>
        );
      })}

      {showCross &&
        (() => {
          /** Wysokość sylwetki nagrobka w x = 0 (gdzie staje stopka krzyża).
           *  Bounding box (= heightM) działa tylko dla rounded i gothic — bo łuk dochodzi do heightM przy x=0.
           *  Classic: quadratic Bezier z punktem kontrolnym (0, heightM) — środek krzywej leży niżej.
           *  Heart: w x = 0 jest „wgłębienie” pomiędzy płatami serca. */
          const headstoneTopAtCenter = (() => {
            switch (shapeKind) {
              case 'classic': {
                const bodyH = Math.max(0.06, heightM - widthM * 0.48);
                const neckY = bodyH * 0.9;
                return (neckY + heightM) / 2;
              }
              case 'heart': {
                const bodyH = Math.max(0.05, heightM - widthM * 0.6);
                const heartTop = heightM * 0.92;
                return bodyH + (heartTop - bodyH) * 0.55;
              }
              /** Asymmetric / tapered (91/83.5 edges, control points at 82.5/103 % H): curve at
               * x = 0 evaluated where the parametric form crosses centre (t ≈ 0.6) → 0.93 · H. */
              case 'asymmetric':
                return heightM * 0.93;
              /** Steep-wave generic (96/78 edges, control points at 100/105 % H): the curve at
               * x = 0 sits near the upper bound, around 0.95 · H. */
              case 'wave-steep':
                return heightM * 0.95;
              /** Dome — apex at (51.8 %, 88.4 % H); at x = 0 the curve is essentially the apex
               * height because the central anchor sits within 2 % of centre. */
              case 'dome':
                return heightM * 0.884;
              /** Arc — at x = 0 the cubic crosses centre near t = 0.5, giving y ≈ 0.844 · H
               *  (peak itself sits left of centre, ≈ 86 % at x ≈ −0.35 · hw). */
              case 'arc':
                return heightM * 0.844;
              /** Cross-top — the body wave crosses x = 0 at t ≈ 0.3, giving y ≈ 85.7 % H. The
               * cross sits on the RIGHT side and is irrelevant for the centre cross
               * decoration mount (decoration `cross` is mutually exclusive with this shape
               * for typical orders, but if both are picked we land on the body's wave). */
              case 'cross-top':
                return heightM * 0.857;
              /** Curvy — apex of the top arch sits at x = 50 % (centre), y = 100 % H, so the
               * cross decoration plants exactly on the apex of the dome. */
              case 'curvy':
                return heightM;
              case 'cross':
              case 'rounded':
              case 'gothic':
              default:
                return heightM;
            }
          })();
          /** Pionowa belka krzyża ma wysokość widthM*0.32 i jest wycentrowana na origin grupy,
           * więc jej dolna krawędź leży w group local Y = -widthM*0.16. Dodajemy ten offset,
           *  żeby stopka krzyża dotykała korony nagrobka (+ drobne zatopienie 5 mm dla schludności). */
          const crossBaseOffset = widthM * 0.16 - 0.005;
          const crossY = headstoneBaseY + headstoneTopAtCenter + crossBaseOffset;
          return (
            <>
              {stelaOffsetsX.map((offsetX, idx) => (
                <group key={`cross-${idx}`} position={[offsetX, crossY, 0]}>
                  <mesh castShadow material={stoneMaterial}>
                    <boxGeometry args={[widthM * 0.06, widthM * 0.32, thicknessM * 0.4]} />
                  </mesh>
                  <mesh castShadow position={[0, widthM * 0.06, 0]} material={stoneMaterial}>
                    <boxGeometry args={[widthM * 0.22, widthM * 0.06, thicknessM * 0.4]} />
                  </mesh>
                </group>
              ))}
            </>
          );
        })()}
    </group>
  );
};
